// SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
// SPDX-License-Identifier: BSD-3-Clause-Open-MPI
// Portions of this file may implement 3GPP specifications, which may be subject to additional licensing requirements.

// SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
// SPDX-License-Identifier: BSD-3-Clause-Open-MPI
// Portions of this file may implement 3GPP specifications, which may be subject to additional licensing requirements.

// =============================================================================
// FILE: include/ocudu/ru/ru_uplink_plane.h  (84 lines)
//
// INTERFACE HEADER — include/ocudu/ru
// Radio Unit (RU) interface headers: upper_ru_dl_rg_handler (receives DL resource grids from the upper PHY for transmission), upper_ru_ul_rx_symbol_handler (delivers received IQ symbols to the upper PHY), the RU configuration interface, and the RU controller (start/stop). The split-8 RU implementation is in lib/ru/sdr; these headers define the contract.
//
// This file defines abstract interfaces / data types used across multiple
// layers. Implementations live in the corresponding lib/ directory.
// =============================================================================

// Portions of this file may implement 3GPP specifications, which may be subject to additional licensing requirements.

#pragma once


#include "ocudu/phy/support/shared_prach_buffer.h"
#include "ocudu/ran/slot_point.h"


namespace ocudu {


struct prach_buffer_context;
struct resource_grid_context;
class shared_resource_grid;

/// Radio Unit uplink received symbol context.

/// Radio Unit uplink received symbol context.
struct ru_uplink_rx_symbol_context {
  /// Slot context.
  /// Slot context.
  slot_point slot;
  /// Radio sector identifier.
  /// Radio sector identifier.
  unsigned sector;
  /// Index, within the slot, of the last processed symbol.
  /// Index, within the slot, of the last processed symbol.
  unsigned symbol_id;
};

/// \brief Radio Unit notifier for events related to received symbols.
///
/// The events generated by this interface are triggered by the requests handled by the \ref ru_downlink_plane_handler
/// interface.

/// \brief Radio Unit notifier for events related to received symbols.
///
/// The events generated by this interface are triggered by the requests handled by the \ref ru_downlink_plane_handler
/// interface.
class ru_uplink_plane_rx_symbol_notifier
{
public:
  /// Default destructor.
  /// Default destructor.
  virtual ~ru_uplink_plane_rx_symbol_notifier() = default;

  /// \brief Notifies the completion of an OFDM symbol for a given context.
  ///
  /// \param[in] context  Notification context.
  /// \param[in] grid     Resource grid that belongs to the context.
  /// \param[in] is_valid Set it to true if the resource grid data contains valid information. Otherwise, set it to
  /// false.

  /// \brief Notifies the completion of an OFDM symbol for a given context.
  ///
  /// \param[in] context  Notification context.
  /// \param[in] grid     Resource grid that belongs to the context.
  /// \param[in] is_valid Set it to true if the resource grid data contains valid information. Otherwise, set it to
  /// false.
  virtual void
  on_new_uplink_symbol(const ru_uplink_rx_symbol_context& context, const shared_resource_grid& grid, bool is_valid) = 0;

  /// \brief Notifies the completion of a PRACH window.
  ///
  /// The Radio Unit uses this method to notify that the PRACH window identified by \c context has been written in \c
  /// buffer.
  ///
  /// \param[in] context PRACH context.
  /// \param[in] buffer  Read-only PRACH buffer.

  /// \brief Notifies the completion of a PRACH window.
  ///
  /// The Radio Unit uses this method to notify that the PRACH window identified by \c context has been written in \c
  /// buffer.
  ///
  /// \param[in] context PRACH context.
  /// \param[in] buffer  Read-only PRACH buffer.
  virtual void on_new_prach_window_data(const prach_buffer_context& context, shared_prach_buffer buffer) = 0;
};

/// \brief Radio Unit uplink plane handler.
///
/// Handles PRACH and uplink data requests and captures uplink data. The uplink received data will be notified through
/// the \ref ru_uplink_plane_rx_symbol_notifier notifier.

/// \brief Radio Unit uplink plane handler.
///
/// Handles PRACH and uplink data requests and captures uplink data. The uplink received data will be notified through
/// the \ref ru_uplink_plane_rx_symbol_notifier notifier.
class ru_uplink_plane_handler
{
public:
  /// Default destructor.
  /// Default destructor.
  virtual ~ru_uplink_plane_handler() = default;

  /// \brief Requests the Radio Unit to capture a PRACH window.
  ///
  /// The Radio Unit must capture a PHY window identified by \c context. The capture must start at slot \c context.slot
  /// and symbol \c context.start_symbol. The capture must finish once \c buffer.is_full() returns true.
  ///
  /// \param[in] context PRACH window context.
  /// \param[in] buffer  PRACH buffer used to write the PRACH window.

  /// \brief Requests the Radio Unit to capture a PRACH window.
  ///
  /// The Radio Unit must capture a PHY window identified by \c context. The capture must start at slot \c context.slot
  /// and symbol \c context.start_symbol. The capture must finish once \c buffer.is_full() returns true.
  ///
  /// \param[in] context PRACH window context.
  /// \param[in] buffer  PRACH buffer used to write the PRACH window.
  virtual void handle_prach_occasion(const prach_buffer_context& context, shared_prach_buffer buffer) = 0;

  /// \brief Requests the Radio Unit to provide an uplink slot.
  ///
  /// The Radio Unit must process the slot described by \c context and notify the demodulation per symbol basis of the
  /// requested slot.
  ///
  /// \param[in] context Resource grid context.
  /// \param[in] buffer  Resource grid to store the processed slot.

  /// \brief Requests the Radio Unit to provide an uplink slot.
  ///
  /// The Radio Unit must process the slot described by \c context and notify the demodulation per symbol basis of the
  /// requested slot.
  ///
  /// \param[in] context Resource grid context.
  /// \param[in] buffer  Resource grid to store the processed slot.
  virtual void handle_new_uplink_slot(const resource_grid_context& context, const shared_resource_grid& grid) = 0;
};


} // namespace ocudu
